### ISSUE TITLE
TODO : menu circulaire

### ISSUE THREAD

**Issue by Sylvain-Mani** [Sylvain-Mani/Styles-laboratory#7]
### Faire un menu circulaire perso : 

inspiré de menu4
- [ ] - placement dynamique en fonction du nombre d'éléments (ajouter une variable pour le calcul des rotations (au lieu de /8))
- [ ] - calculer dynamiquement le nombre d'éléments (js et affecter la valeur à la variable css)
- [ ] - réglages de l'écartement des éléments (jouer sur la value translateY des span avec une variable)
- [ ] - trouver comment élargir la zone de drag
- [ ] - rajouter drag sur l'axe X
